previewsEnabled: false

services:
  - type: web
    name: gyandeep
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVarFilePath: gyandeep.env
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000